services:
  - type: web
    name: waslny-app
    runtime: docker
    repo: https://github.com/mouhamamd-kl/waslny.git # Ensure this is your correct repo URL
    region: frankfurt # Optional, choose a region close to you
    plan: free # Or your desired plan
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    # The start command will be handled by the CMD in the Dockerfile
    preDeployCommand: "php artisan migrate --force"
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      # Add your non-sensitive env vars here
      # ---
      # IMPORTANT: Add the following as secrets in your Render environment:
      # APP_KEY
      # DB_HOST
      # DB_PORT
      # DB_DATABASE
      # DB_USERNAME
      # DB_PASSWORD
      # REDIS_HOST
      # REDIS_PASSWORD
      # REDIS_PORT
      # PUSHER_APP_ID
      # PUSHER_APP_KEY
      # PUSHER_APP_SECRET
